apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: external-connectivity
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 3
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
     - name: kafka
       port: 9092
     - name: external
       external:
         enabled: true
          # The subdomain need to be managed externally for example by
          # External-DNS. In AWS provider there is fix to expose public IP
          # https://github.com/kubernetes-sigs/external-dns/pull/1391
         subdomain: "test.subdomain.com"
    adminApi:
    - port: 9644
    developerMode: true
