apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindNodeCache: true
kindContainers:
  - gcr.io/vectorized/redpanda-k8s-operator:latest
testDirs:
  - ./tests/e2e
kindConfig: ./kind.yaml
commands:
  - command: "kubectl apply -k config/default"
artifactsDir: tests/_e2e_artifacts
timeout: 300
