name: package_creation_handler
on:
  repository_dispatch:
    types: [packages-created]

jobs:
  package_creation_handler:
    runs-on: ubuntu-20.04

    steps:
      - name: Notify PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.VTOOLS_GITHUB_API_TOKEN }}
          issue-number: ${{ github.event.client_payload.pr_number }}
          body: |
            Packages created for ${{ github.event.client_payload.ref }}
            Tests requiring them can now be run. Try:
            `/chaos-test` or `/ducktape`
        if: ${{ github.event.client_payload.pr_number }}
